apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devplatform-gateway
  namespace: dev-platform
  labels:
    app: devplatform-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: notypie.dev
      http:
        paths:
          - pathType: Prefix
            path: /apiservice(/|$)(.*)
            backend:
              service:
                name: devplatform-gateway
                port:
                  number: 80
